# Generated by Django 5.2 on 2025-04-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='price',
        ),
    ]
