# Generated by Django 5.2 on 2025-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_precio_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hub',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='hub',
            field=models.ManyToManyField(related_name='products', to='main.hub'),
        ),
    ]
