# Generated by Django 5.2 on 2025-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_category_remove_product_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hub',
            field=models.ManyToManyField(to='main.hub'),
        ),
    ]
